import streamlit as st

st.title("📚 Our Courses")

st.write("""
Welcome to our comprehensive course catalog. We offer a range of programs designed to enhance your skills and knowledge:

- **MS-CIT with Including AI** — Maharashtra's official IT literacy course
- **Tally Prime with GST** — Manage your business accounting with tally prime
- **Typing with GCC TBC** — Master typing skills with government certification
- **Skill Development** — Courses in Typing, Excel, and PowerPoint
- **KLiC Courses** — Access to all 244 certified KLiC courses
"""
)

klic_courses = [
    "KLiC Certificate in Basics of Accounting with Tally",
    "KLiC Certificate in Foundation of Financial Accounting (Tally and Excel)",
    "KLiC Certificate in Office Assistance",
    "KLiC Certificate in Office Assistance with Soft Skills",
    "KLiC Certificate in Basic Data Management with Excel",
    "KLiC Certificate in Basics of Accounting & Service Entrepreneurship",
    "KLiC Certificate in Basics of Accounting and Digital Freelancing",
    "KLiC Certificate in Photo Editing",
    "KLiC Certificate in Content Illustration",
    "KLiC Certificate in Video Editing",
    "KLiC Certificate in 3D Modeling",
    "KLiC Certificate in AutoCAD",
    "KLiC Certificate in Teaching Digital Arts",
    "KLiC Certificate in Digital Freelancing",
    "KLiC Certificate in English Language Skills & Communication Skills",
    "KLiC Certificate in Soft Skills",
    "KLiC Certificate in IT Hardware Support",
    "KLiC Certificate in IT Network Support",
    "KLiC Certificate in IT Desktop Support",
    "KLiC Certificate in IT Desktop and Security Support",
    "KLiC Certificate in Retail Management",
    "KLiC Certificate in Banking Financial Services Insurance (BFSI)",
    "KLiC Certificate in Management Basics",
    "KLiC Certificate in Social Media Marketing",
    "KLiC Certificate in Customer Focus",
    "KLiC Certificate in Service Designing and Operations",
    "KLiC Certificate in Managing Service Operations",
    "KLiC Certificate in Service Entrepreneurship",
    "KLiC Certificate in Service Quality",
    "KLiC Certificate in Management Basics with Soft Skills",
    "KLiC Certificate in Service Entrepreneurship with English and Soft Skills",
    "KLiC Certificate in Digital Freelancing with Social Media Marketing",
    "KLiC Certificate in Service Entrepreneurship and Social Media Marketing",
    "KLiC Certificate in Customer Focus with Understanding Customer Requirement",
    "KLiC Certificate in C Programming",
    "KLiC Certificate in C++ Programming",
    "KLiC Certificate in Mobile App Development Basics",
    "KLiC Certificate in C Programming & Java",
    "KLiC Certificate in Tally Prime with GST",
    "KLiC Certificate in Data Entry and Data Management",
    "KLiC Certificate in Advanced Excel",
    "KLiC Certificate in Advanced Data Management with Excel",
    "KLiC Certificate in Data Management with Advanced MS Excel",
    "KLiC Certificate in Advanced Excel and Google Workspace",
    "KLiC Certificate in Advanced Excel with DBMS",
    "KLiC Certificate in Advanced Digital Freelancing",
    "KLiC Certificate in Digital Freelancing and Google Workspace",
    "KLiC Certificate in Digital Freelancing and Data Analytics & Data Visualisation",
    "KLiC Certificate in Social Media Marketing and Data Analytics",
    "KLiC Certificate in Graphic Designing",
    "KLiC Certificate in Desk Top Publishing (CorelDraw)",
    "KLiC Certificate in Desk Top Publishing (Adobe)",
    "KLiC Certificate in Web Designing",
    "KLiC Certificate in 3D Texturing and Lightning",
    "KLiC Certificate in Use of Graphics for Video Editing",
    "KLiC Certificate in AutoCAD and 3D Modeling",
    "KLiC Certificate in 3D Modeling and Texturing & Lighting",
    "KLiC Certificate in Graphic and Web Designing",
    "KLiC Certificate in 3D Modeling, Animation and VFX",
    "KLiC Certificate in Video Editing, Animation and VFX",
    "KLiC Certificate in 3D Modeling and Game Development",
    "KLiC Certificate in Scratch and Internet of Things (IoT)",
    "KLiC Certificate in Advanced Hardware & Networking",
    "KLiC Certificate in Robotics",
    "KLiC Certificate in IT Security Support & Cyber Security",
    "KLiC Certificate in Robotics and IoT",
    "KLiC Certificate in IT Hardware and Cloud Computing",
    "KLiC Certificate in Advanced Retail Management",
    "KLiC Certificate in Advanced Banking, Financial Services & Insurance (BFSI)",
    "KLiC Certificate in Service Entrepreneurship with Data Management",
    "KLiC Certificate in Service Entrepreneurship and Data Management with Excel",
    "KLiC Certificate in Service Entrepreneurship and Data Analytics & Data Management",
    "KLiC Certificate in Mobile App Development",
    "KLiC Certificate in Python",
    "KLiC Certificate in Data Structures using C- C++",
    "KLiC Certificate in Java",
    "KLiC Certificate in C#",
    "KLiC Certificate in Database Management Systems",
    "KLiC Certificate in Mobile App Development with Web Designing",
    "KLiC Certificate in Web and Database Administrator & DBMS",
    "KLiC Certificate in Mobile App and Server API Development",
    "KLiC Certificate in PHP with HTML and CSS",
    "KLiC Certificate in PHP with DBMS",
    "KLiC Certificate in PHP with Web Designing",
    "KLiC Certificate in PHP with Server API Development",
    "KLiC Certificate in Java Programming and Server API Development",
    "KLiC Certificate in Advanced Tally Pro",
    "KLiC Certificate in Applied Advanced Accounting (Tally and Excel)",
    "KLiC Data Analytics & Data Visualisation",
    "KLiC Certificate in Data Visualisation",
    "KLiC Certificate in Excel with Python Programming for Data Analysis",
    "KLiC Certificate in Advanced Desk Top Publishing",
    "KLiC Certificate in Advanced Web Designing",
    "KLiC Certificate in Animation/VFX",
    "KLiC Certificate in Revit",
    "KLiC Certificate in Game Development (Unity 3D)",
    "KLiC Certificate in AutoCAD and Revit",
    "KLiC Cloud Computing Essentials",
    "KLiC Web and Database Administrator",
    "KLiC Certificate in HTML with CSS",
    "KLiC Certificate in PHP",
    "KLiC Certificate in Software Development and Deployment Tools",
    "KLiC Certificate in Front End Development",
    "KLiC Certificate in Server API Development",
    "KLiC Certificate in Mobile App Development & Java Programming",
    "KLiC Certificate in Mobile App Development & CSS with HTML",
    "KLiC Certificate in Java Programming with CSS & HTML",
    "KLiC Certificate in Java with Server API Development",
    "KLiC Certificate in Data Analytics and Data Visualisation with Python",
    "KLiC Certificate in Data Analytics and Data Visualisation with DBMS",
    # ...add the rest of your 244 courses here
]

st.write("**KLiC Courses:**")
for course in klic_courses:
    st.write(f"- {course}")

st.image("https://via.placeholder.com/700x300?text=Courses", use_column_width=True)
